### ISSUE TITLE
Crash on Misc Settings

### ISSUE THREAD

**Issue by jatinhariani** [BrianEstrada/PokeScanner#211]
Reporting from a build from master branch:

```
08-03 15:33:36.526 30348-30348/com.pokescanner.alpha E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.pokescanner.alpha, PID: 30348
                                                                       Theme: themes:{default=overlay:com.quarttz.impress.mind, iconPack:system, fontPkg:system, com.android.systemui=overlay:com.quarttz.impress.mind, com.android.systemui.navbar=overlay:com.quarttz.impress.mind}
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pokescanner.alpha/com.pokescanner.settings.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
                                                                           at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:188)
                                                                           at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:181)
                                                                           at com.pokescanner.settings.SettingsFragment.setupMiscOptions(SettingsFragment.java:258)
                                                                           at com.pokescanner.settings.SettingsFragment.onCreateView(SettingsFragment.java:134)
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2220)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
                                                                           at android.app.FragmentController.execPendingActions(FragmentController.java:325)
                                                                           at android.app.Activity.performStart(Activity.java:6267)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Could be nothing. Putting this here in case it is of any help.

**Comment by BrianEstrada** [comment]
I had this error too, I'm pretty sure it should be fixed now.
